use_frameworks!
platform :ios, '12.0'

target 'ChatBird_Example' do
  pod 'ChatBird', :path => '../'
  pod 'SendBirdSDK'
  pod 'Chatto'
  pod 'ChattoAdditions'

  target 'ChatBird_Tests' do
    inherit! :search_paths

    
  end
end
